language: node_js
sudo: required
node_js:
  - "8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
      # This is required to run new chrome on old trusty
    - libnss3
      # Add python3 dependencies to run transifex-client
    - python3
    - python3-pip

before_script:
    - TEST=true npm run build


deploy: #update translation strings on transifex
    provider: script
    skip_cleanup: true
    script: bash .tx/push.sh
    on:
      branch: master
