language: node_js
sudo: required
node_js:
  - "8"
dist: xenial
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
      # Add python3 dependencies to run transifex-client
    - python3.5
    - python3-pip
    - python3-setuptools

before_script:
    - npm install eslint --save-dev
    - TEST=true npm run build -- --mode=production

script:
    - ./node_modules/.bin/eslint `find src -type f -name "*.js" | grep -v '/libs/import_masq.js'`
    - npm run test

deploy: #update translation strings on transifex
    provider: script
    skip_cleanup: true
    script: bash .tx/push.sh
    on:
      branch: master
